### ISSUE TITLE
number of participants on 24th June workshop and relevant info such as age/experience

### ISSUE THREAD

**Issue by melvinzhang** [melvinzhang/ai-python-course#7]
@julbee Do you have more details on the 24th June participants? This weekend will be the main push to finish up the content. If you have the info, it will be easier for me to customize.

**Comment by julbee** [comment]
At the moment, 5 adults who can understand Python code.
ᐧ

Educating All for the Future,

Juliana Ung
LccL Coding Academy
19 Tanglin Road #05-49/50, Singapore 247909
M: +65 96918603 <+65%209691%208603> T: +65 68172957
W: lcclcoding.com Instagram: lcclcoding
<https://www.instagram.com/lcclcoding/>
FB: facebook.com/lcclcoding

**Comment by melvinzhang** [comment]
Thanks for the info! All the while I was under the impression that it will be students.
