### ISSUE TITLE
reaching lccl early in Sunday to test and do other checks

### ISSUE THREAD

**Issue by melvinzhang** [melvinzhang/ai-python-course#8]
@julbee this workshop is a bit heavy on the setup, part of it can be done through tmate but part of it I need to see the desktop and other parts of the system. What's the earliest I can come by to test it out on the macs on Sunday?

**Comment by melvinzhang** [comment]
I did some checks and it may be possible to do it remotely. Can you enable remote access as described in https://help.ubuntu.com/community/AppleRemoteDesktop?

**Comment by julbee** [comment]
We will be at lccl 9am onwards on Sunday. Come in anytime. Do you still need remote access? If so, will it be on the one you are using or students' too?

**Comment by melvinzhang** [comment]
@julbee Thanks on Sunday I will come before lunch, perhaps around 10am. I will use remote desktop on Saturday. Do you have IPv6 addresses at LCCL?

**Comment by melvinzhang** [comment]
Update laptop to hold have the file the attendees need. Create the package with `make ai-python-workshop.zip`
